ci:
    collect:
        staticDistDir: dist
        numberOfRuns: 3
        settings:
            preset: desktop

    assert:
        preset: lighthouse:no-pwa
        assertions:
            non-composited-animations: off

    upload:
        target: lhci
        serverBaseUrl: https://lhci.arnelle.dev/
