ci:
  collect:
    staticDistDir: build
    numberOfRuns: 3
    settings:
      preset: desktop

  assert:
    preset: lighthouse:no-pwa

  upload:
    target: lhci
    serverBaseUrl: https://lhci.arnelle.me/
