export const TODOS_TODAY = 'TODAY';
export const TODOS_THIS_WEEK = 'THIS_WEEK';
export const TODOS_EVENTUALLY = 'EVENTUALLY';

export const TODOS_DATE_ABSOLUTE = 'DATE_ABSOLUTE';
export const TODOS_DATE_RELATIVE = 'DATE_RELATIVE';
