name: Check lighthouse scores
on:
  push:
    branches:
      - main
      - 'release/**'
jobs:
  check-scores:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: cp .env.ci .env
      - run: npm run build
      - run: npm run lhci -- --upload.token=$LHCI_BUILD_TOKEN
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          LHCI_BUILD_TOKEN: ${{ secrets.LHCI_BUILD_TOKEN }}
